name: My Workflow

on: [push]

jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: echo "Secret is ${YOUTUBE_API_KEY:0:5}"

      - name: Print global env var
        env:
          GLOBAL_ENV_VAR: ${{ secrets.GLOBAL_ENV_VAR }}
        run: echo "Global env var is $GLOBAL_ENV_VAR"
